language: bash
sudo: false

before_script:
  - bash ./script/git.sh

script:
  - bash ./script/build.sh

deploy:
  provider: firebase
  token:
    secure: "YOUR ENCRYPTED token"

env:
  global:
  - secure: GS+2po+or+ryTmwRicW7vlcr0zX7ySDRUXIDbfxpcrtQpQr7EU7RAZU/tKX/1d/BJgmf7s0OJyJudrywHGs15U/qV/wDm43Il2kOXAi51smpleCcHJFPBPwxEUuRVabHdyZRo1WNJbAARoLm+wGYxBNlfLEvi9hSR1uLxDx5irAT1YNDxwAahnWqOUCtk5RR1xZSO94kS0c2BiTd1FG2EKcimqZdzebtg7ugFCKiyy3wVU62InjI8wlDMNZeFzYt15eh5SKXKTbD5fDP3jviE/IsoqPQQqccWk8euqepTA4b6Er3YkftfPw7Fb1GChwqZV7KsVUUMpzE++Eih46Z3rEr5UBDIg3Lvo15HjqAh/cfgkMlTakavLyXzJU4sLuYZyfEmUo5J/lJc98EQAypqmqON3Apy1QH66IhvDPBZ88/CY081MC+7Tr1INQRo+Uku1FKBbM/Sf0AWPTeXJHZkipVzmZ7I7cF2EJYwfDNKAqS6Uz4ZXvZVb7NRMLcn6IoJ4NGPDaFucF9FCVzyPvPRnK38D+sBYJdLweJ1/uem62KTkQOJcayQpwFciWPOFpymRNyZ44A/p3MnnXkJo2ZKV+VVun8EuDEMpIai9de0Lgl49490WbHepXcF5YNUieGmZ7lwH2ALKLi413s9gTO97ZyPgW9lEtkap5Cf7RAyf4=
