baseurl = "https://blog.haramishio.xyz/"
languageCode = "ja"
title = "ハラミTech"
googleAnalytics = "UA-73777852-1"
DisqusShortname = "haramitech"

[[menu.main]]
    name = "post"
    url = "/post"
    
[[menu.main]]
    name = "rss"
    url = "/index.xml"

[Author]
    name = "Morix"
    bio = "インフラエンジニアです。でもいろんな分野に興味がある！"
    avatar = "/profile.jpg"

[Params]
    subtitle = "ぎじゅつ9割 にく1割"
    description = "Webやサーバーの技術についての調査やアプリ作成についてのブログを発信しています。"
    hasCJKLanguage = true
    authorbox = true
    post_navigation = true

[Params.widgets]
    recent_articles = true
    recent_articles_num = 10
    tags = true

    social_twitter = "morix1500"
    social_github = "morix1500"
    social_qiita = "Morix1500"